{
  "hash": "ed5688cc9006a41f1e37f8d5b86795dd",
  "result": {
    "markdown": "---\ntitle: \"Day 2B\"\nformat:\n  html:\n    css: ../styles.css\n    highlight-style: github\n---\n\n\n![](../img/growth_curve_2780E3.svg){.hero}\n\n\nWe continue after lunch with an overview of estimating and probing linear models in R. We will learn the R formula syntax for fitting simple regression, multiple regression, regression with categorical predictors, and regression with interaction effects (i.e., moderation). We will also cover regression diagnostics and easy ways to address common assumption violations. If there is time, we will end with a brief introduction to simple power analysis techniques for $t$-tests, ANOVAs, and regression models.\n\n## Slides\n\n<iframe class=\"slide-deck\" src=\"./Slides/2B_Slides.html\" title=\"Day 2B Slideshow\">\n</iframe>\n\n[Click here to view the slides in their own window.](./Slides/2B_Slides.html)\n\n## Data Files\n\n- <a href=\"yearspubs.csv\" download=\"yearspubs.csv\">yearspubs</a> (professors' salaries by seniority, publications, etc.)\n- <a href=\"exercise.csv\" download=\"exercise.csv\">exercise</a> (fake data weight loss from different exercise programs)\n- <a href=\"political.csv\" download=\"political.csv\">political</a> (students' political and voting behavior)\n\n## Practice 1\n\na) Download the `political` dataset from the link above, move it to your project folder, and read it into R. Update the tibble to set the `sex` variable as a factor (0=Male, 1=Female). \n\nb) Create histograms to view the distributions of the `informed` and `tv_news` variables and a bar plot to view the counts of the `sex` variable. What do these distributions look like?\n\nc) Build a regression model to predict each student's self-reported level of political informedness (`informed`) from the degree to which they watch television news (`tv_news`). What is the standardized slope for the television news predictor? *Bonus:* What is the model's adjusted R-squared?\n\nd) Expand your regression model from Question 1(b) to become a multiple regression model that also includes students' sex (`sex`) as a predictor. What are the two predictor variables' partial effects?\n\ne) Statistically test whether the effect of television watching depends on students' sex and generate a plot that shows the model's predictions (to help you interpret any interaction effect).\n\n<p><details>\n<summary>Click here for the answer key</summary>\n<blockquote>\n\n**Answer (a)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\npolitical <- read_csv(\"political.csv\")\n\npolitical$sex <- factor(\n  political$sex, \n  levels = c(0, 1), \n  labels = c(\"Male\", \"Female\")\n)\n```\n:::\n\n\n**Answer (b)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqplot(x = informed, data = political, geom = \"histogram\")\n```\n\n::: {.cell-output-display}\n![](day2B_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqplot(x = tv_news, data = political, geom = \"histogram\")\n```\n\n::: {.cell-output-display}\n![](day2B_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n```{.r .cell-code}\nqplot(x = sex, data = political, geom = \"bar\")\n```\n\n::: {.cell-output-display}\n![](day2B_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n:::\n\n\nThe `informed` variable is discrete at 1, 2, 3, 4, or 5 with a triangular pattern where 3 is most common. The `tv_news` variable is discrete at 0, 1, 2, 3, or 4 with a pattern where 0 and 3 are most common. The `sex` variable is relatively balanced between male and female.\n\n**Answer (c)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\nfit <- lm(informed ~ tv_news, data = political)\nmodel_parameters(fit, standardized = \"refit\")\n#> Parameter   | Coefficient |   SE |       95% CI | t(57) |      p\n#> ----------------------------------------------------------------\n#> (Intercept) |        2.64 | 0.17 | [2.31, 2.97] | 15.97 | < .001\n#> tv news     |        0.21 | 0.07 | [0.07, 0.36] |  3.02 | 0.004\nmodel_performance(fit)\n#> # Indices of model performance\n#> \n#> AIC     |    AICc |     BIC |    R2 | R2 (adj.) |  RMSE | Sigma\n#> ---------------------------------------------------------------\n#> 151.237 | 151.673 | 157.469 | 0.138 |     0.123 | 0.829 | 0.843\n```\n:::\n\n\nThe standardized slope is 0.21 for `tv_news` and it is significantly different from zero $(p=.004)$. This simple model explains 12% of the variance in `informed` $(R^2_{adj}=0.123)$.\n\n**Answer (d)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- lm(informed ~ tv_news + sex, data = political)\nmodel_parameters(fit2)\n#> Parameter    | Coefficient |   SE |         95% CI | t(56) |      p\n#> -------------------------------------------------------------------\n#> (Intercept)  |        2.88 | 0.20 | [ 2.48,  3.28] | 14.55 | < .001\n#> tv news      |        0.20 | 0.07 | [ 0.06,  0.34] |  2.87 | 0.006 \n#> sex [Female] |       -0.44 | 0.22 | [-0.87, -0.01] | -2.06 | 0.044\n```\n:::\n\n\nThe partial effect of television news was $0.20$ and the partial effect of sex was $-0.44$ (females reported feeling/being less informed than males).\n\n**Answer (e)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit3 <- lm(informed ~ tv_news * sex, data = political)\nmodel_parameters(fit3)\n#> Parameter              | Coefficient |   SE |        95% CI | t(55) |      p\n#> ----------------------------------------------------------------------------\n#> (Intercept)            |        2.90 | 0.23 | [ 2.44, 3.35] | 12.69 | < .001\n#> tv news                |        0.19 | 0.09 | [ 0.01, 0.37] |  2.10 | 0.041 \n#> sex [Female]           |       -0.48 | 0.33 | [-1.13, 0.18] | -1.46 | 0.149 \n#> tv news × sex [Female] |        0.02 | 0.14 | [-0.27, 0.31] |  0.14 | 0.887\nplot(estimate_relation(fit3))\n```\n\n::: {.cell-output-display}\n![](day2B_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe effect of television news does not seem to depend on sex, as the interaction effect was not significant $(p=.887)$ and the prediction lines were very close to parallel.\n\n</blockquote></details></p>\n\n## Practice 2\n\nUse regression diagnostics to check the model from Practice 1 part (e). Are there any obvious issues with this model (e.g., violated assumptions, outliers, multicollinearity)?\n\n<p><details>\n<summary>Click here for the answer key</summary>\n<blockquote>\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(fit3)\n```\n\n::: {.cell-output-display}\n![](day2B_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\nDue to the use of a single Likert-style item for the outcome variable, the observed `informed` values do not look normal at all (see the posterior predictive check). Additionally, there appears to be some heteroskedasticity with the error variance increasing at the highest fitted values. However, the other checks look okay to me.\n</blockquote></details></p>\n\n## Practice 3\n\nImagine I want to run a study comparing the spatial recognition memory of currently depressed patients and non-depressed controls. I found a meta-analysis ([Rock et al., 2014](https://doi.org/10/f58cfq)) that estimated this difference to be $d=−0.41$. Use \\{WebPower\\} to determine how many participants I should recruit in each group in order to have 80\\% power to detect an effect of this size with $\\alpha=.05$.\n\n<p><details>\n<summary>Click here for the answer key</summary>\n<blockquote>\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(WebPower)\nwp.t(\n  power = 0.80,\n  alpha = 0.05,\n  type = \"two.sample\",\n  d = -0.41\n)\n## Two-sample t-test\n## \n##            n    d alpha power\n##     94.35326 0.41  0.05   0.8\n## \n## NOTE: n is number in *each* group\n## URL: http://psychstat.org/ttest\n```\n:::\n\nEach group would need around 94 participants (so around 188 total).\n\n</blockquote></details></p>\n\n## Readings\n\n  -   [Chapter 5: Basic Regression](https://moderndive.com/5-regression.html) from *ModernDive*\n  -   [Chapter 6: Multiple Regression](https://moderndive.com/6-multiple-regression.html) from *ModernDive*\n  -   [Chapter 10: Inference for Regression](https://moderndive.com/10-inference-for-regression.html) from *ModernDive*\n  -   [Checking model assumptions - linear models](https://easystats.github.io/performance/articles/check_model.html) from *performance* package website\n  -   [WebPower Manual](https://webpower.psychstat.org/wiki/manual/index) from Zhang \\& Yuan\n  ",
    "supporting": [
      "day2B_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}