{
  "hash": "4b44d432c5eac836d4e644d476521aed",
  "result": {
    "markdown": "---\ntitle: \"Day 2A\"\nformat:\n  html:\n    css: ../styles.css\n    highlight-style: github\n---\n\n\n![](../img/statistics_2780E3.svg){.hero}\n\nWe resume on Day 2 with a discussion of special data types (for categorical data and missing values), data summarization and exploration, and basic statistical inference. The latter will include various types of correlation, two-sample tests for comparing two groups, and oneway tests for comparing multiple groups.\n\n## Slides\n\n<iframe class=\"slide-deck\" src=\"./Slides/2A_Slides.html\" title=\"Day 2A Slideshow\">\n</iframe>\n\n[Click here to view the slides in their own window.](./Slides/2A_Slides.html)\n\n## Data Files\n\n- <a href=\"yearspubs.csv\" download=\"yearspubs.csv\">yearspubs</a> (professors' salaries by seniority, publications, etc.)\n- <a href=\"salaries.csv\" download=\"salaries.csv\">salaries</a> (professors' salaries by rank, discipline, etc.)\n- <a href=\"interpersonal.csv\" download=\"interpersonal.csv\">interpersonal</a> (patients' interpersonal problems before and after treatment)\n- <a href=\"elicitation.csv\" download=\"elicitation.csv\">elicitation</a> (participants' emotions elicited during different tasks)\n\n## Practice\n\n## Question 1.\n\na) Download the `yearspubs` dataset from the link above and read it into R.\n\nb) Estimate the correlation between academics' number of publications (`n_pubs`) and number of citations (`n_cites`) in this sample.\n\nc) Compare the average number of citations between male and female academics using a Welch t-test. Which group had more and was the difference significant?\n\nd) Estimate the effect size of this difference.\n\n<p><details>\n<summary>Click here for the answer key</summary>\n<blockquote>\n\n**Answer (a)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nyearspubs <- read_csv(\"yearspubs.csv\")\n```\n:::\n\n\n\n**Answer (b)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\ncorrelation(yearspubs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Correlation Matrix (pearson-method)\n\nParameter1      | Parameter2 |    r |       95% CI | t(60) |         p\n----------------------------------------------------------------------\nyears_since_phd |     n_pubs | 0.65 | [0.48, 0.78] |  6.70 | < .001***\nyears_since_phd |    n_cites | 0.37 | [0.14, 0.57] |  3.11 | 0.007**  \nyears_since_phd |     salary | 0.51 | [0.29, 0.67] |  4.54 | < .001***\nn_pubs          |    n_cites | 0.34 | [0.10, 0.54] |  2.80 | 0.007**  \nn_pubs          |     salary | 0.43 | [0.21, 0.62] |  3.72 | 0.002**  \nn_cites         |     salary | 0.38 | [0.15, 0.58] |  3.19 | 0.007**  \n\np-value adjustment method: Holm (1979)\nObservations: 62\n```\n:::\n:::\n\n\nThe correlation between number of publications and citations is 0.34.\n\n**Answer (c)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- t.test(\n  formula = n_cites ~ sex,\n  data = yearspubs\n)\nmodel_parameters(results)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Unable to retrieve data from htest object.\n  Returning an approximate effect size using t_to_d().\n```\n:::\n\n::: {.cell-output-display}\nTable: Welch Two Sample t-test\n\n|Parameter | Group | Mean_Group1 | Mean_Group2 | Difference |         95% CI |     d | CI_low.1 | CI_high.1 | t(60.00) |     p |\n|:---------|:-----:|:-----------:|:-----------:|:----------:|:--------------:|:-----:|:--------:|:---------:|:--------:|:-----:|\n|n_cites   |   sex |       37.33 |       42.46 |      -5.12 | (-13.60, 3.36) | -0.31 |   -13.60 |      3.36 |    -1.21 | 0.232 |\n\nAlternative hypothesis: true difference in means between group female and group male is not equal to 0\n:::\n:::\n\n\nGroup 2 (Males) had more citations (42.46) than Group 1 (Females) had (37.33) but this difference was not significant ($p=.232$).\n\n**Answer (d)**\n\nThe effect size was $d=-0.31$ but the difference was not significant $(p=.232)$.\n\n</blockquote></details></p>\n\n\n## Question 2\n\nUsing the `mpg` tibble from the \\{tidyverse\\} package, statistically test whether cars with the three different drive trains (`drv`) get significantly different city fuel efficiency (`cty`) on average. Calculate the effect size for this difference.\n\n<p><details>\n<summary>Click here for the answer key</summary>\n<blockquote>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- aov(formula = cty ~ drv, data = mpg)\nmodel_parameters(results, effectsize_type = \"eta\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n|Parameter | Sum_Squares |  df | Mean_Square |     F |      p | Eta2 |\n|:---------|:-----------:|:---:|:-----------:|:-----:|:------:|:----:|\n|drv       |     1878.81 |   2 |      939.41 | 92.68 | < .001 | 0.45 |\n|Residuals |     2341.53 | 231 |       10.14 |       |        |      |\n\nAnova Table (Type 1 tests)\n:::\n:::\n\n\nThe effect size was $\\eta^2=0.45$ and the difference was significant $(p<.001)$.\n\n</blockquote></details></p>\n\n\n## Question 3.\n\nDid you bring your own data? If so, load it into R and explore it using the tools we learned this week. Wrangle it a bit and maybe do some basic statistics on it, estimating correlations and comparing group means.\n\n## Readings\n\n  -   [Chapter 15: Factors](https://r4ds.had.co.nz/factors.html) from *R4DS (2E)*\n  -   [Part IV: Statistical Theory](https://learningstatisticswithr.com/book/part-iv-statistical-theory.html) from *LSWR*\n  -   [Part V: Statistical Tools](https://learningstatisticswithr.com/book/index.html) from *LSWR*\n  -   [Correlation Types](https://easystats.github.io/correlation/articles/types.html) from *correlation* package website\n  -   [Estimate Means](https://easystats.github.io/modelbased/articles/estimate_means.html) from *modelbased* package website\n  -   [Estimate Contrasts](https://easystats.github.io/modelbased/articles/estimate_contrasts.html) from *modelbased* package\n\n::: {.text-center}\n<a href=\"day2B.html\" class=\"btn btn-primary mt-5\" role=\"button\" >Continue to Day 2B Materials&nbsp;&nbsp;&raquo;</a>\n:::\n",
    "supporting": [
      "day2A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}